### ISSUE TITLE
Option for setting the jvm 

### ISSUE THREAD

**Issue by yasargil** [sbtrun-maven-plugin/sbtrun-maven-plugin#13]
In our multi module maven build we have the requirement to build some Scala projects with java 8 and some with java 7.
Is it possible to add another configuration which goes into the Java Task Creation:
```
Java javaTask = new Java();
javaTask.setJvm(jvmpath)
```

```
<execution>
  <id>compile</id>
  <phase>compile</phase>
  <goals>
      <goal>run</goal>
  </goals>
  <configuration>
     <jvmpath>path to jvm</jvmpath>
     <args>compile</args>
  </configuration>
</execution>
```

**Comment by gslowikowski** [comment]
Could you create simple test project?

**Comment by yasargil** [comment]
Here you go:
https://github.com/yasargil/sbt-run-test

mvn clean on the sbt-run-test-java7 with java 8 fails and with java 7 it works
mvn clean on the sbt-run-test-java8 with java 8 works with java 7 it fails

**Comment by gslowikowski** [comment]
Using this plugin for Play2 projects is not a good idea. Try [play2-maven-plugin](https://github.com/play2-maven-plugin/play2-maven-plugin/) and you will see large performance boost and your test project will build with Java8.

I've prepared modified version of your test project [here](https://github.com/gslowikowski/sbt-run-test).

Your real projects have much more complicated SBT build files than this one for sure :) Try `play2-maven-plugin` and if you will find something, you cannot port to pure Maven build, let me know.

Additionally, I wonder why you need two build system for one project.

**Comment by yasargil** [comment]
Hi

- With the play2-maven-plugin how does the dependency resolution work? Is ivy still involved? 
- We use the "com.eed3si9n" % "sbt-buildinfo" % "0.6.1" buildinfo plugin, how would the configuration work with the play2-maven-plugin?

```
lazy val root = (project in file(".")).enablePlugins(PlayJava, BuildInfoPlugin).settings(
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion, "builtAt" -> {
      val dtf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
      dtf.setTimeZone(java.util.TimeZone.getTimeZone("UTC"))
      dtf.format(new java.util.Date())
    }
    ),
    buildInfoPackage := "buildinfo"
  ).settings(
        publishArtifact in (Compile, packageDoc) := false,
        publishArtifact in packageDoc := false,
        sources in (Compile,doc) := Seq.empty
    )
```

> Additionally, I wonder why you need two build system for one project.

We don't. We have multiple modules in our project some are play 2.1 and some are of a newer play version mixed with pure java modules. The test projects are just stripped down versions of them. And yes they are a lot more complex and unfortunately some are not so easy to upgrade to newer play version.

Anyway thank you for your time and i will look into the play2-maven-plugin.

**Comment by gslowikowski** [comment]
Dependency resolution is pure Maven (much faster).

BuildInfoPlugin - I don't know if it can be replaced by something from Maven world, I never used it. Can you add it to the test project, you created? I will check it.

**Comment by yasargil** [comment]
> Dependency resolution is pure Maven (much faster).

Oh great.

> BuildInfoPlugin - I don't know if it can be replaced by something from Maven world, I never used it. Can you add it to the test project, you created? I will check it.

I did add it to the sbt-run-test-java8 project.

**Comment by yasargil** [comment]
Do you haven any idea what is going wrong. I am on mac with 10.12.5. The app will not respond after the last log output.

```
mvn play2:run -Dplay2.httpPort=9002
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OEV DDS Management 4.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- play2-maven-plugin:1.0.0-beta8:run (default-cli) @ oev-dds-management ---
[WARNING] File watch service initialization failed. Running without hot-reload functionality.
java.lang.NullPointerException
	at com.google.code.play2.watcher.jnotify.JNotifyFileWatchService.copyResourceToFile(JNotifyFileWatchService.java:202)
	at com.google.code.play2.watcher.jnotify.JNotifyFileWatchService.initialize(JNotifyFileWatchService.java:124)
	at com.google.code.play2.plugin.Play2RunMojo.internalExecute(Play2RunMojo.java:478)
	at com.google.code.play2.plugin.AbstractPlay2Mojo.execute(AbstractPlay2Mojo.java:139)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9002
[INFO] 
[INFO] (Server started, use [Enter] to stop...)
[INFO] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OEV DDS Management 4.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- play2-maven-plugin:1.0.0-beta8:routes-compile (default-routes-compile) @ oev-dds-management ---
[INFO] Generating injected router
[INFO] 1 router processed, 1 compiled
[INFO] 
[INFO] --- play2-maven-plugin:1.0.0-beta8:template-compile (default-template-compile) @ oev-dds-management ---
[INFO] 13 templates processed, 13 compiled
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ oev-dds-management ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 3 resources to public
[INFO] 
[INFO] --- sbt-compiler-maven-plugin:1.0.0:compile (default-compile) @ oev-dds-management ---
[INFO] Compiling 17 Scala sources and 10 Java sources to /Users/yasargil/java/webplattform/oev-dds-module/oev-dds-management/target/classes...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.452 s
[INFO] Finished at: 2017-05-30T12:01:58+02:00
[INFO] Final Memory: 67M/830M
[INFO] ------------------------------------------------------------------------
Exception in thread "ForkJoinPool-1-worker-1" java.lang.UnsatisfiedLinkError: no jnotify in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.contentobjects.jnotify.macosx.JNotify_macosx.<clinit>(Unknown Source)
	at net.contentobjects.jnotify.macosx.JNotifyAdapterMacOSX.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
	at com.google.code.play2.watcher.jnotify.JNotifyFileWatcher.<init>(JNotifyFileWatcher.java:58)
	at com.google.code.play2.watcher.jnotify.JNotifyFileWatchService.watch(JNotifyFileWatchService.java:169)
	at com.google.code.play2.plugin.MavenPlay2Builder.build(MavenPlay2Builder.java:373)
	at com.google.code.play2.provider.play25.run.Reloader.reload(Reloader.java:76)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:123)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:121)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by gslowikowski** [comment]
Strange, I don't have a Mac but I have Mac users of my plugin. I will analyze this problem.

Temporary workaround is to force different file watch service - [jdk7](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta8/play2-source-watchers/play2-source-watcher-jdk7/usage.html) or [polling](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta8/play2-source-watchers/play2-source-watcher-polling/usage.html). They both are slower, than JNotify (that's why JNotify is used by default on Mac), but should work without problems.

**Comment by gslowikowski** [comment]
[Maven version of test project](https://github.com/gslowikowski/sbt-run-test) updated.

**Comment by yasargil** [comment]
Great Thanks.

> Strange, I don't have a Mac but I have Mac users of my plugin. I will analyze this problem.

Should i open an issue on the plugin page with de debug log?

**Comment by gslowikowski** [comment]
Will you help me find the problem?

**Comment by yasargil** [comment]
I will try

**Comment by gslowikowski** [comment]
OK, create an issue. We will continue there.

**Comment by gslowikowski** [comment]
Are you satisfied with [play2-maven-plugin](https://github.com/play2-maven-plugin/play2-maven-plugin/)?

**Comment by yasargil** [comment]
Yeah. I use it in one of our play projects and its is working great. Especially build time because it does not need to resolve dependencies with ivy and sbt, also the inclusion in the maven build is a big plus. I have some other play projects which i want to convert to the plugin when i find the time for it.

Thank you

**Comment by gslowikowski** [comment]
Great.

 I don't want to implement your original request and will close this issue.

When adding a possibility to set JVM path it would be natural to add [Maven toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) support as well.
Unfortunately, this would complicate plugin's code and dependencies leading to (possible) goals execution slow down.
If this functionality will be required in the future by someone, I will return to it.
